config/routes.rb
Rails.application.routes.draw do
  get 'tasks/action'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

get '/tasks', to: 'tasks#index'
# get '/tasks', to:
get '/tasks/new', to: 'tasks#new'
post '/tasks', to: 'tasks#create'


get '/tasks/:id', to: 'tasks#show', as: :task

delete '/tasks/:id', to: 'tasks#destroy', as: :destroy_task

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    # @task = Task.find(params[:id].to_i)
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.create(task_strong_params)
    redirect_to task_path(task)
  end

  def destroy
    # @task = Task.find(params[:id].to_i)
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_strong_params
    params.require(:task).permit(:title, :description, :completed)
  end

  def set_task
    @task = Task.find(params[:id].to_i)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>Tasks#action</h1>
<p>Find me in app/views/tasks/action.html.erb</p>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <% if task.completed %>
        <input type = "checkbox" checked>
      <% else %>
        <input type = "checkbox">
      <% end %>
      <%= task.title %>
    </li>
    <%= link_to 'show', task_path(task)  %>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<%= form_for(@task) do |task| %>
  <%= task.label :title %>
  <%= task.text_field :title %>
  <br>
  <%= task.label :details %>
  <%= task.text_field :details %>
  </br>
  <%= task.submit %>
  <br>
  <%= link_to 'back to homepage', tasks_path %>
  </br>
<% end %>

app/views/tasks/show.html.erb
<ul>
    <li>
      <% if @task.completed %>
        <input type = "checkbox" checked>
      <% else %>
        <input type = "checkbox">
      <% end %>
      <%= @task.title %>
    </li>
    <p><%= link_to 'destroy this task',  destroy_task_path(@task), method: :delete, data: { confirm: 'are you sure?'} %></p>
    <p><%= link_to 'back to the list', tasks_path %></p>

</ul>